# Generated by Django 5.0.2 on 2024-02-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_operationlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='operationlog',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='user_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='user_username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
